# Generated by Django 3.2.9 on 2021-12-10 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecrypto',
            name='date_added_as_fav',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 18, 55, 44, 200471, tzinfo=utc)),
        ),
    ]
