# Generated by Django 3.2.9 on 2021-12-10 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 19, 0, 12, 898813, tzinfo=utc)),
        ),
    ]
