# Generated by Django 3.2.9 on 2021-12-10 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20211210_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 21, 3, 47, 207473, tzinfo=utc)),
        ),
    ]
