# Generated by Django 3.2.9 on 2021-11-16 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211116_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 7, 1, 37, 357756, tzinfo=utc)),
        ),
    ]
