# Generated by Django 3.2.9 on 2021-12-11 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_auto_20211211_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotification',
            name='member_notified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagenotification_member_notified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagenotification_message', to='messaging.message'),
        ),
    ]
